- id: python-docstrings
  name: Check Python API documentation
  description: Require Python documentation; optionally include tests and scan extra folders.
  entry: python-docstrings
  language: python
  types: [python]

- id: java-javadocs
  name: Check Java API documentation
  description: Require Java documentation; optionally include tests and scan extra folders.
  entry: java-javadocs
  language: python
  types: [java]
  additional_dependencies: [tree-sitter==0.25.2, tree-sitter-java==0.23.5]

- id: csharp-xml-docs
  name: Check C# API documentation
  description: Require C# documentation; optionally include tests and scan extra folders.
  entry: csharp-xml-docs
  language: python
  types: [c#]
  additional_dependencies: [tree-sitter==0.25.2, tree-sitter-c-sharp==0.23.1]
